Add janzell to the list of contributors
devcreatives/first_contribution pull request #121
Opened 2021-09-21 05:49 UTC by janzell

2021-09-21 05:55 UTC, CodingSpecies requested changes

2021-09-21 05:55 UTC, CodingSpecies commented on Data/member.json
> +    	}
Please can you move that forward a tab @janzell please?

2021-09-21 05:55 UTC, CodingSpecies commented on Data/member.json
> +	    {
@janzell after you move the bottom closing brace, please move the whole section you wrote one tab back, so its formatted like the rest of the file. Thank you.

2021-10-25 07:28 UTC, NS007-dev requested changes
@janzell you have conflicts, please can they be resolved, and if you need any help, feel free to ask. Thank you.

2021-12-14 12:34 UTC, TheSlimCoder approved these changes
I resolved conflicts by myself,
Thank you for contributing.

2021-12-14 12:34 UTC, merged

2021-12-14 12:34 UTC, TheSlimCoder commented
@all-contributors add @janzell for code.