Added AkshayHere
devcreatives/first_contribution pull request #142
Opened 2021-10-25 05:18 UTC by AkshayHere

2021-10-25 06:48 UTC, NS007-dev requested changes

2021-10-25 06:48 UTC, NS007-dev commented on Data/member.json
> +        },
Please remove the comma after the brace on line 496 @AkshayHere

2021-10-25 07:27 UTC, NS007-dev requested changes

2021-10-25 07:27 UTC, NS007-dev commented on Data/member.json
> +	{
@AkshayHere Please can you also align the braces, so they are formatted?

2021-10-25 07:27 UTC, NS007-dev approved these changes
Thank you for fixing this. Just fix the review I placed above, and it should be fine @AkshayHere

2021-10-25 07:34 UTC, AkshayHere commented
Formatted the JSON file to maintain coding standards

2021-10-25 07:38 UTC, NS007-dev approved these changes
~~I am not sure how all of it got deleted, but it seems as though you have restored them all.~~
Thank you for fixing it! @AkshayHere 
We will have to wait for a maintainer to merge this.

2021-10-25 07:41 UTC, NS007-dev commented
> 
> 
> Formatted the JSON file to maintain coding standards


Thank you for formatting the whole file! I just realised that! Thank you for that! I forgot to say that it was only for line 490, but thank you for doing the whole file @AkshayHere

2021-10-25 07:42 UTC, AkshayHere commented
> 
> 
> > Formatted the JSON file to maintain coding standards
> 
> Thank you for formatting the whole file! I just realised that! Thank you for that! I forgot to say that it was only for line 490, but thank you for doing the whole file @AkshayHere

Sure. I would recommend adding some ESLint features to standardize the code across the repo.

2021-10-25 07:43 UTC, NS007-dev commented
> 
> 
> > > Formatted the JSON file to maintain coding standards
> > 
> > 
> > Thank you for formatting the whole file! I just realised that! Thank you for that! I forgot to say that it was only for line 490, but thank you for doing the whole file @AkshayHere
> 
> Sure. I would recommend adding some ESLint features to standardize the code across the repo.

Yes, it has been said in this issue #134

2021-10-25 07:46 UTC, AkshayHere commented
> 
> 
> > > > Formatted the JSON file to maintain coding standards
> > > 
> > > 
> > > Thank you for formatting the whole file! I just realised that! Thank you for that! I forgot to say that it was only for line 490, but thank you for doing the whole file @AkshayHere
> > 
> > 
> > Sure. I would recommend adding some ESLint features to standardize the code across the repo.
> 
> Yes, it has been said in this issue #134

Great :). Thanks for the same.

2021-12-14 12:37 UTC, TheSlimCoder approved these changes
Looks Good

2021-12-14 12:37 UTC, TheSlimCoder commented
@AkshayHere you need to work on conflicts and formatting then I will merge it.

2022-11-28 07:02 UTC, closed without merging