feat: add thuongtruong1009 to member list json
devcreatives/first_contribution pull request #157
Opened 2022-01-27 16:06 UTC by thuongtruong1009

I updated some things.

2022-01-27 22:37 UTC, CodingSpecies approved these changes

2022-05-09 11:49 UTC, TheSlimCoder approved these changes

2022-05-09 11:49 UTC, TheSlimCoder commented
@thuongtruong1009 can you please resolve conflicts?

2022-06-05 10:46 UTC, CodingSpecies requested changes
@thuongtruong1009 this pr is only one step away from being merged. In order for it to be merged please can you resolve the conflicts? Thank you.

2022-06-06 04:04 UTC, thuongtruong1009 commented
> @thuongtruong1009 can you please resolve conflicts?

I made a new PR at https://github.com/devcreatives/first_contribution/pull/168

2022-06-06 04:04 UTC, closed without merging